package server

import (
	"errors"
)

var (
	ErrInternalError      = errors.New("internal error")
	ErrGenID              = errors.New("gen ID failed")
	ErrDupDatabase        = errors.New("duplicate database")
	ErrDupTable           = errors.New("duplicate table")
	ErrDupNode            = errors.New("duplicate node")
	ErrNotExistDatabase   = errors.New("database not exist")
	ErrNotExistTable      = errors.New("table not exist")
	ErrTableIsDeleted     = errors.New("table is deleted")
	ErrNotExistNode       = errors.New("node not exist")
	ErrNotExistMac        = errors.New("machine not exist")
	ErrNotExistZone       = errors.New("zone not exist")
	ErrNotExistRange      = errors.New("range not exist")
	ErrNotExistPeer       = errors.New("range peer not exist")
	ErrForbidSplit        = errors.New("range forbid split")
	ErrForbidSchedul      = errors.New("range forbid schedul")
	ErrNotLeader          = errors.New("range peer not leader")
	ErrNoLeader           = errors.New("range has no leader")
	ErrNotEnoughResources = errors.New("not enough resources")
	ErrInvalidParam       = errors.New("invalid param")
	ErrInvalidColumn      = errors.New("invalid column")
	ErrColumnNameTooLong  = errors.New("column name is too long")
	ErrDupColumnName      = errors.New("duplicate column name")
	ErrPkMustNotNull      = errors.New("primary key must be not nullable")
	ErrMissingPk          = errors.New("missing primary key")
	ErrPkMustNotSetDefaultValue = errors.New("primary key should not set defaultvalue")
	ErrRaftNetSplit       = errors.New("raft net split")
	ErrNodeFault          = errors.New("node is fault")
	ErrNotExistTask       = errors.New("task not exist")
	ErrTooManyTask       = errors.New("to many task")
	ErrStaleEpoch         = errors.New("stale epoch")
	ErrSchedulerExisted   = errors.New("scheduler is existed")
	ErrSchedulerNotFound  = errors.New("scheduler is not found")
	ErrInvalidUrl         = errors.New("invalid url")
	ErrAlarmerBusy        = errors.New("alarmer busy")
	ErrPusherBusy         = errors.New("pusher busy")
	ErrNotExistColumn     = errors.New("column not exist")
	ErrSqlReservedWord    = errors.New("sql reserved word")
	ErrBrokenChannel      = errors.New("broken channel")
	ErrInvalidChannel     = errors.New("invalid channel")
	ErrClosedChannel      = errors.New("closed channel")
	ErrBadRequest         = errors.New("bad request")
	ErrBadResponse        = errors.New("bad response")
	ErrUnExpectedResponse = errors.New("unexpected http response")
	ErrColumnIdTooBig     = errors.New("column id is too big")
	ErrColumnTtlDatatype  = errors.New("column ttl type error ")
	ErrSQLSyntaxError     = errors.New("Syntax error")
	ErrTaskConflictState  = errors.New("task state conflict")
	ErrDupDeploy          = errors.New("dup deploy")
)
